// Code generated by "stringer -type=TokenType"; DO NOT EDIT

package elmlexer

import "fmt"

const _TokenType_name = "TokenErrorTokenEOFTokenCommentTokenLeftParenTokenRightParenTokenLeftBracketTokenRightBracketTokenLeftBraceTokenRightBraceTokenPipeTokenInfixOpTokenColonTokenAssignTokenCommaTokenArrowTokenIdentifierTokenOpTokenStringTokenIntTokenFloatTokenKeywordTokenRangeTokenCharTokenBoolTokenDot"

var _TokenType_index = [...]uint16{0, 10, 18, 30, 44, 59, 75, 92, 106, 121, 130, 142, 152, 163, 173, 183, 198, 205, 216, 224, 234, 246, 256, 265, 274, 282}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
